### ISSUE TITLE
Video from workshop

### ISSUE THREAD

**Issue by seltmann** [Big-Bee-Network/name-alignment-workshop#23]
@jtmiller28 A video from the workshop is now available to link on the workshop page: https://vimeo.com/manage/videos/790959610

**Comment by jtmiller28** [comment]
Video has been embedded into the workshop main website page (see index.md). Firefox has some issues due to using FLASH instead of HTML5. A fix can be found here: http://techawakening.org/vimeo-videos-not-working-in-firefox-solution/2490/ if interested, alternatively opening in a different search browser will show the video (only tested with chrome at the moment). Closing issue for now.
